# Generated by Django 5.1.1 on 2024-09-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('Loanid', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Accountno', models.IntegerField()),
                ('Salary', models.IntegerField()),
                ('Loanamt', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
